kind: ConfigMap
metadata:
  name: grafana-agent-traces
apiVersion: v1
data:
  agent.yaml: |
    logs:
      configs:
      - name: WebShop-Logs
        clients:
        - url: <loki_url>
          basic_auth:
            username: <loki_username>
            password: <loki_password>
          external_labels:
            cluster: web-shop
            job: tracelogs
        positions:
          filename: /tmp/positions.yaml
        target_config:
          sync_period: 10s
    traces:
        configs:
          - batch:
                send_batch_size: 1000
                timeout: 5s
            name: default
            service_graphs:
                enabled: true
            receivers:
                otlp:
                    protocols:
                        grpc: null
                        http: null
            spanmetrics:
              dimensions:
                - name: http.method
                - name: http.target
                - name: team.name
              handler_endpoint: 0.0.0.0:1234
            automatic_logging:
              backend: logs_instance
              logs_instance_name: WebShop-Logs
              roots: true
              processes: true
              spans: true
              span_attributes:
                - http.method
                - http.target
                - http.status_code
              overrides:
                trace_id_key: "traceId"
            remote_write:
              - basic_auth:
                    password: <tempo_password>
                    username: <tempo_username> 
                endpoint: <tempo_url>
                retry_on_failure:
                    enabled: false
            scrape_configs:
              - bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
                job_name: kubernetes-pods
                kubernetes_sd_configs:
                  - role: pod
                relabel_configs:
                  - action: replace
                    source_labels:
                      - __meta_kubernetes_namespace
                    target_label: namespace
                  - action: replace
                    source_labels:
                      - __meta_kubernetes_pod_name
                    target_label: pod
                  - action: replace
                    source_labels:
                      - __meta_kubernetes_pod_container_name
                    target_label: container
                tls_config:
                    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                    insecure_skip_verify: false
  strategies.json: '{"default_strategy": {"param": 0.001, "type": "probabilistic"}}'

